### ISSUE TITLE
Change external_repository to secrets.EXTERNAL_REPOSITORY in gh-pages.yml

### ISSUE THREAD

**Issue by chidoriashi1990** [chidoriashi1990/portfoliem#53]
## Before
```yaml
- name: deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.PERSONAL_TOKEN }}
    external_repository: chidoriashi1990/chidoriashi1990.github.io
    publish_branch: master
    publish_dir: ./dist
```

## After
```yaml
- name: deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.PERSONAL_TOKEN }}
    external_repository: ${{ secrets.EXTERNAL_REPOSITORY }}
    publish_branch: master
    publish_dir: ./dist
```
